"""add phone number to users table

Revision ID: 295389db9b78
Revises: 64504c1ebb17
Create Date: 2022-09-06 22:58:26.680053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295389db9b78'
down_revision = '64504c1ebb17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
